# @package _global_

half: False
grad_scaler: True
device: 'cuda:0'
seed: 2525
progress_bar: True

save_model: False
save_interval: 10

epochs: 100
val_every: 1
es_patience: 100000
es_min_delta: 0.0001
es_metric: 'Train/crossentropyloss'
scheduler_metric: 'Train/crossentropyloss'
optimized_metric: "Val/Accuracy"