# @package dataset

name: "MNIST"

load_params:
  root: "${storage_dir}"
  train: false
  download: true
save_in_memory: true

shuffle: false
batch_size: 512
num_workers: 0
pin_memory: true
drop_last: false

subset: 0.0


transform: general/mnist

